
package org.esb.opensource.coc;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF (incubator) 2.0.5-incubator
 * Sun Apr 13 14:50:56 CEST 2008
 * Generated source version: 2.0.5-incubator
 * 
 */
 
public class CoCPortType_CoCSoap_Server{

    protected CoCPortType_CoCSoap_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new CoCPortTypeImpl();
        String address = "http://localhost:8080";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new CoCPortType_CoCSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exitting");
        System.exit(0);
    }
}
